export default {
    Home: "Trang chủ",
    DateOfRelease: "Năm phát hành",
    Genres: "Thể loại",
    Country: "Quốc gia",
    Actor: "Diễn viên",
    StarRating: "Đánh giá",
    MovieDescription: "Nội dung phim",
    Comments: "Bình luận",
    RelatedMovies: "Các phim liên quan",
    New: "Mới",
    Featured_Movies: "Phim đặc sắc",
    Featured: "Đặc sắc",
    Top_Viewed: "Lượt xem nhiều",
    Top_Rating: "Đánh giá cao",
    Recently_Added: "Thêm gần đây",
    Successful: "Successful",
    Fail: "Fail",
    TypeToastSuccess: 'success',
    TypeToastWarning: 'warning',
    TypeToastError: 'error',
    TypeToastInfo: 'info',
    TypeToastDefault: 'default',
    TopToast: 'top',
    BottomToast: 'bottom',
    TopRightToast:'top-right',
    TopLeftToast:'top-left',
    BottomRightToast:'bottom-right',
    BottomLeftToast:'bottom-left',

}